
language: cpp

os:
    - osx
    - linux

matrix:
    include:
        - os: osx
          osx_image: xcode8
          compiler:
              - clang

          before_install:
              - ./ci/install_deps_osx.sh

          cache:
              directories:
                  - $HOME/Library/Caches/Homebrew

        - os: linux
          dist: xenial
          before_install:
              - sudo apt-get -qq update
              - sudo apt-get install -y cmake libsdl2-dev libsdl2-ttf-dev liblua5.2-dev libboost-system-dev libboost-filesystem-dev


jobs:
  include:
    - stage:  c++format
      script: ./ci/clang-format.sh
    - stage:  build
      script: ./build.py